var resources = [];
resources['demo.Title'] = "பரவல் ஆர்ப்பாட்டம்";
resources['demo.Row1'] = "ரோ ஒரு உள்ளடக்கத்தை";
resources['demo.Row2'] = "ரோ இரண்டு உள்ளடக்கத்தை";
resources['demo.Row3'] = "வரிசையில் மூன்று உள்ளடக்கம்";
resources['demo.Row4'] = "ரோ நான்கு உள்ளடக்கம்";
resources['demo.Row5'] = "ரோ ஐந்து உள்ளடக்கம்";
resources['demo.Row6'] = "ரோ ஐந்து உள்ளடக்கம்";
resources['demo.Row7'] = "ரோ ஐந்து உள்ளடக்கம்";