var resources = [];
resources['demo.Title'] = "Démonstration de localisation";
resources['demo.Row1'] = "Row une contenu";
resources['demo.Row2'] = "Row deux contenu";
resources['demo.Row3'] = "Row trois contenu";
resources['demo.Row4'] = "Row quatre contenu";
resources['demo.Row5'] = "Row cinq contenu";
resources['demo.Row6'] = "Row six contenu";
resources['demo.Row7'] = "Row sept contenu";