var resources = [];
resources['demo.Title'] = "Localization demo";
resources['demo.Row1'] = "Row one content";
resources['demo.Row2'] = "Row two content";
resources['demo.Row3'] = "Row three content";
resources['demo.Row4'] = "Row four content";
resources['demo.Row5'] = "Row five content";
resources['demo.Row6'] = "Row six content";
resources['demo.Row7'] = "Row seven content";