var resources = [];
resources['demo.Title'] = "Localization demo";
resources['demo.para'] = "This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.";
resources['demo.inbox'] = "Inbox";
resources['demo.sent'] = "Sent Items";
resources['demo.trash'] = "Trash";
resources['demo.more'] = "More";
resources['demo.Row6'] = "Row six content";
resources['demo.Row7'] = "Row seven content";
